# Generated by Django 4.2.2 on 2023-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('skype', models.CharField(max_length=32)),
                ('whatsapp', models.CharField(max_length=64)),
                ('telegram', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(max_length=10)),
                ('related_services', models.ManyToManyField(to='landing_backend.services')),
            ],
        ),
    ]
