# Generated by Django 4.2.2 on 2023-06-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_backend', '0002_companycontacts_services_servicetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetypes',
            name='price',
            field=models.IntegerField(),
        ),
    ]
