# Generated by Django 4.2.2 on 2023-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_backend', '0003_alter_servicetypes_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontacts',
            name='inn',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
