# Generated by Django 4.2.2 on 2023-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_backend', '0004_companycontacts_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='company_name',
            field=models.CharField(max_length=80, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='email',
            field=models.CharField(max_length=32, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='inn',
            field=models.CharField(max_length=15, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='skype',
            field=models.CharField(max_length=32, verbose_name='Логин Skype'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='telegram',
            field=models.CharField(max_length=32, verbose_name='Логин Telegram'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='whatsapp',
            field=models.CharField(max_length=64, verbose_name='Номер Whatsapp'),
        ),
    ]
