# Generated by Django 4.2.2 on 2023-06-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_backend', '0006_alter_possibilities_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/partners', verbose_name='Партнер')),
            ],
        ),
        migrations.AlterField(
            model_name='possibilities',
            name='image',
            field=models.ImageField(upload_to='images/possibilities', verbose_name='Изображение'),
        ),
    ]
